# Generated by Django 3.2.17 on 2023-05-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='medicoId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='consultas.medico'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='pacienteId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='consultas.paciente'),
        ),
        migrations.AlterField(
            model_name='cuentapaciente',
            name='pacienteId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='consultas.paciente'),
        ),
    ]
