# Generated by Django 3.2.17 on 2023-05-09 21:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_auto_20230505_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCita', models.DateTimeField(default=datetime.datetime.now)),
                ('sintomas', models.TextField(max_length=500)),
                ('diagnostico', models.TextField(max_length=500)),
                ('tratamiento', models.TextField(max_length=500)),
                ('idCIta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='consultas.citas')),
                ('medicoId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='consultas.medico')),
                ('pacienteId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='consultas.paciente')),
            ],
        ),
    ]
