# Generated by Django 3.2.17 on 2023-05-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='idCIta',
            new_name='idCita',
        ),
        migrations.AddField(
            model_name='consulta',
            name='ejecutada',
            field=models.BooleanField(default=False),
        ),
    ]
