# Generated by Django 3.2.17 on 2023-05-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_auto_20230510_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='ejecutada',
        ),
        migrations.AddField(
            model_name='citas',
            name='ejecutada',
            field=models.BooleanField(default=False),
        ),
    ]
