# Generated by Django 3.2.17 on 2023-05-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_auto_20230510_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='cobrada',
            field=models.BooleanField(default=False),
        ),
    ]
