# Generated by Django 3.2.17 on 2023-06-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0007_cuentapaciente_idcita'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='ciudadCita',
            field=models.CharField(choices=[('Colima', 'Colima'), ('Guadalajara', 'Guadalajara'), ('Tijuana', 'Tijuana'), ('México', 'México'), ('Monterrey', 'Monterrey'), ('Cd. Guzman', 'Cd. Guzman')], default='Colima', max_length=40),
        ),
    ]
