# Generated by Django 3.2.17 on 2023-06-20 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_citas_ciudadcita'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='apellidosTutor',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apmaterno',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='celularTutor',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='correo',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='paciente',
            name='entidad',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='facebook',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fechaNac',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='paciente',
            name='instagram',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='paciente',
            name='municipio',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombreTutor',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pagweb',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pais',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='poblacion',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefonoTutor',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='domicilio',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sintomas',
            field=models.CharField(default='', max_length=100),
        ),
    ]
