# Generated by Django 3.2.17 on 2023-06-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0009_auto_20230619_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellidosTutor',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celularTutor',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombreTutor',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefonoTutor',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
